ERROR 2018-10-05 01:00:03,971 base 22595 140527851128576 Internal Server Error: /api/v1/posts/
Traceback (most recent call last):
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/home/will/git/django/google_material/django_angular/posts/views.py", line 18, in perform_create
    serializer.save(author=self.request.user)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 180, in save
    self.instance = self.create(validated_data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 832, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: NOT NULL constraint failed: posts_post.rating
ERROR 2018-10-05 01:00:58,967 base 22802 139663425234688 Internal Server Error: /api/v1/posts/
Traceback (most recent call last):
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/home/will/git/django/google_material/django_angular/posts/views.py", line 18, in perform_create
    serializer.save(author=self.request.user)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 180, in save
    self.instance = self.create(validated_data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 832, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: NOT NULL constraint failed: posts_post.rating
ERROR 2018-10-05 01:01:18,849 base 22802 139663342827264 Internal Server Error: /api/v1/posts/
Traceback (most recent call last):
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/home/will/git/django/google_material/django_angular/posts/views.py", line 18, in perform_create
    serializer.save(author=self.request.user)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 180, in save
    self.instance = self.create(validated_data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 832, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: NOT NULL constraint failed: posts_post.rating
ERROR 2018-10-05 01:01:57,694 base 22877 140616222635776 Internal Server Error: /api/v1/posts/
Traceback (most recent call last):
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/home/will/git/django/google_material/django_angular/posts/views.py", line 18, in perform_create
    serializer.save(author=self.request.user)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 180, in save
    self.instance = self.create(validated_data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 832, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: NOT NULL constraint failed: posts_post.rating
ERROR 2018-10-05 01:25:45,725 base 25486 140051980875520 Internal Server Error: /api/v1/posts/
Traceback (most recent call last):
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 663, in data
    ret = super(ListSerializer, self).data
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 228, in data
    self._data = self.to_representation(self.instance)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 603, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 448, in to_representation
    fields = self._readable_fields
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 342, in _readable_fields
    field for field in self.fields.values()
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 328, in fields
    for key, value in self.get_fields().items():
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 922, in get_fields
    field_name, info, model, depth
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1045, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1146, in build_unknown_field
    (field_name, model_class.__name__)
ImproperlyConfigured: Field name `rating` is not valid for model `Post`.
ERROR 2018-10-05 01:28:22,070 base 25486 140051766834944 Internal Server Error: /api/v1/posts/
Traceback (most recent call last):
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 663, in data
    ret = super(ListSerializer, self).data
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 228, in data
    self._data = self.to_representation(self.instance)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 603, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 448, in to_representation
    fields = self._readable_fields
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 342, in _readable_fields
    field for field in self.fields.values()
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 328, in fields
    for key, value in self.get_fields().items():
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 922, in get_fields
    field_name, info, model, depth
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1045, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1146, in build_unknown_field
    (field_name, model_class.__name__)
ImproperlyConfigured: Field name `rating` is not valid for model `Post`.
ERROR 2018-10-05 01:28:49,103 base 25486 140051989268224 Internal Server Error: /api/v1/posts/
Traceback (most recent call last):
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 663, in data
    ret = super(ListSerializer, self).data
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 228, in data
    self._data = self.to_representation(self.instance)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 603, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 448, in to_representation
    fields = self._readable_fields
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 342, in _readable_fields
    field for field in self.fields.values()
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 328, in fields
    for key, value in self.get_fields().items():
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 922, in get_fields
    field_name, info, model, depth
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1045, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1146, in build_unknown_field
    (field_name, model_class.__name__)
ImproperlyConfigured: Field name `rating` is not valid for model `Post`.
ERROR 2018-10-05 01:29:37,867 base 25486 140051989268224 Internal Server Error: /api/v1/posts/
Traceback (most recent call last):
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 663, in data
    ret = super(ListSerializer, self).data
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 228, in data
    self._data = self.to_representation(self.instance)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 603, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 448, in to_representation
    fields = self._readable_fields
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 342, in _readable_fields
    field for field in self.fields.values()
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 328, in fields
    for key, value in self.get_fields().items():
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 922, in get_fields
    field_name, info, model, depth
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1045, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1146, in build_unknown_field
    (field_name, model_class.__name__)
ImproperlyConfigured: Field name `rating` is not valid for model `Post`.
ERROR 2018-10-05 01:29:47,881 base 25486 140051766834944 Internal Server Error: /api/v1/posts/
Traceback (most recent call last):
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 663, in data
    ret = super(ListSerializer, self).data
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 228, in data
    self._data = self.to_representation(self.instance)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 603, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 448, in to_representation
    fields = self._readable_fields
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 342, in _readable_fields
    field for field in self.fields.values()
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 328, in fields
    for key, value in self.get_fields().items():
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 922, in get_fields
    field_name, info, model, depth
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1045, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1146, in build_unknown_field
    (field_name, model_class.__name__)
ImproperlyConfigured: Field name `rating` is not valid for model `Post`.
ERROR 2018-10-05 01:34:07,647 base 25486 140051980875520 Internal Server Error: /api/v1/posts/
Traceback (most recent call last):
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 20, in create
    serializer.is_valid(raise_exception=True)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 202, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 396, in run_validation
    value = self.to_internal_value(data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 420, in to_internal_value
    fields = self._writable_fields
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 335, in _writable_fields
    field for field in self.fields.values()
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 328, in fields
    for key, value in self.get_fields().items():
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 922, in get_fields
    field_name, info, model, depth
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1045, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1146, in build_unknown_field
    (field_name, model_class.__name__)
ImproperlyConfigured: Field name `rating` is not valid for model `Post`.
ERROR 2018-10-05 01:34:30,073 base 25486 140051980875520 Internal Server Error: /api/v1/posts/
Traceback (most recent call last):
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 20, in create
    serializer.is_valid(raise_exception=True)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 202, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 396, in run_validation
    value = self.to_internal_value(data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 420, in to_internal_value
    fields = self._writable_fields
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 335, in _writable_fields
    field for field in self.fields.values()
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 328, in fields
    for key, value in self.get_fields().items():
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 922, in get_fields
    field_name, info, model, depth
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1045, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1146, in build_unknown_field
    (field_name, model_class.__name__)
ImproperlyConfigured: Field name `rating` is not valid for model `Post`.
ERROR 2018-10-05 01:34:49,965 base 25486 140051733001984 Internal Server Error: /api/v1/posts/
Traceback (most recent call last):
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 20, in create
    serializer.is_valid(raise_exception=True)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 202, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 396, in run_validation
    value = self.to_internal_value(data)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 420, in to_internal_value
    fields = self._writable_fields
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 335, in _writable_fields
    field for field in self.fields.values()
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 328, in fields
    for key, value in self.get_fields().items():
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 922, in get_fields
    field_name, info, model, depth
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1045, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 1146, in build_unknown_field
    (field_name, model_class.__name__)
ImproperlyConfigured: Field name `rating` is not valid for model `Post`.
ERROR 2018-10-05 01:36:48,878 base 25486 140051758180096 Internal Server Error: /admin/posts/post/
Traceback (most recent call last):
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/template/base.py", line 1273, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py", line 311, in result_list
    headers = list(result_headers(cl))
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py", line 102, in result_headers
    return_attr=True
  File "/home/will/git/django/google_material/env/local/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 342, in label_for_field
    raise AttributeError(message)
AttributeError: Unable to lookup 'rating' on Post or PostAdmin
